name: kanetest
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  image_picker: ^0.8.4+1
  dio: ^4.0.4
  intl: ^0.17.0
  flutter_pin_code_fields: ^2.2.0
  get: ^4.6.5
  sqflite: ^2.3.0
  path_provider: ^2.0.2





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0








flutter:
  uses-material-design: true
  assets:
    - images/image1.webp
    - images/image2.webp
    - images/image3.webp
    - images/image4.webp
    - images/image5.webp
    - images/image6.webp
    - images/image7.webp
    - images/login.png
    - images/wechat.png
    - images/apple.png
    - images/sign.png
    - images/order1.png
    - images/order2.png
    - images/order3.png
    - images/order4.png
    - images/order5.png
    - images/me1.png
    - images/me2.png
    - images/me3.png
    - images/me4.png
    - images/me5.png
    - images/me6.png
    - images/me7.png
    - images/me10.png
    - images/message1.png
    - images/message2.png
    - images/message3.png
    - images/bottom1.png
    - images/bottom2.png
    - images/bottom3.png
    - images/bottom4.png
    - images/grey1.png
    - images/grey2.png
    - images/grey3.png
    - images/grey4.png
    - images/HomeDetails.png
    - images/woman.png
    - images/telegram.png
    - images/wechat2.png
    - images/alipay.png
    - images/select.png
    - images/select1.png
    - images/message4.png
    - images/noDate.png
    - images/bang.png
    - images/bang2.png
