name: kanetest
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0




flutter:
  uses-material-design: true
  assets:
    - images/image1.webp
    - images/image2.webp
    - images/image3.webp
    - images/image4.webp
    - images/image5.webp
    - images/image6.webp
    - images/image7.webp
    - images/login.png
    - images/wechat.png
    - images/apple.png
    - images/sign.png
